project_id = "hwygdowejlmqtemnzjnf"

[functions.send-order-confirmation]
verify_jwt = false

[functions.notify-comment]
verify_jwt = false

[functions.send-blog-digest]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false